# Generated by Django 5.1.7 on 2025-03-14 17:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='basket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
