# Generated by Django 5.1.7 on 2025-03-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_alter_order_basket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='basket_id',
            field=models.UUIDField(),
        ),
    ]
