# Generated by Django 5.1.7 on 2025-03-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_order_cancel_reason_order_msg_for_couriers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='basket_id',
            field=models.UUIDField(unique=True),
        ),
    ]
