# Generated by Django 5.1.7 on 2025-03-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_alter_order_basket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
