# Generated by Django 5.2 on 2025-05-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_orderitem_sku_alter_orderitem_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store_id',
            field=models.IntegerField(null=True),
        ),
    ]
